PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
?uri ?p ?o
}
WHERE {
  <http://semantic.digital-agenda-data.eu/def/property/breakdown> qb:codeList [ skos:hasTopConcept ?uri ] .
  ?uri ?p ?o
}
