PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX dad-prop: <http://semantic.digital-agenda-data.eu/def/property/>

SELECT * where {
?observation
    a qb:Observation ; 
    ?p ?value1;
    ?p ?value2.

FILTER (?value1 != ?value2 )
}