PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dad-prop: <http://semantic.digital-agenda-data.eu/def/property/> 

select distinct ?ind ?area ?time where { 
  ?obs a qb:Observation; qb:dataSet <http://semantic.digital-agenda-data.eu/dataset/digital-agenda-scoreboard-key-indicators> .

  ?obs dad-prop:indicator [skos:notation ?ind];
       dad-prop:ref-area ?area;
       dad-prop:time-period ?time .

  FILTER (?area = <http://eurostat.linked-statistics.org/dic/geo#EU28>)
  FILTER (lcase(?ind) IN (
  	"i_isk_ge_me",
		"h_bbfix",
		"h_broad",
		"h_iacc",
		"h_xcost",
		"househ",
		"i_atsw",
		"i_barr1x",
		"i_bfeu",
		"i_bgood",
		"i_bgoodo",
		"i_blt12",
		"i_bpgood",
		"i_bserv",
		"i_cc",
		"i_cook",
		"i_cprg",
		"i_cprg1",
		"i_cweb",
		"i_iday",
		"i_igov12rt",
		"i_igov12rt",
		"i_igovrt",
		"i_ihif",
		"i_ilt12",
		"i_iu3",
		"i_iu3g",
		"i_iu3g1",
		"i_iubk",
		"i_iueduif",
		"i_iugm",
		"i_iugmv",
		"i_iugov",
		"i_iugov12",
		"i_iuhd_mphbb",
		"i_iuif",
		"i_iujob",
		"i_iumapp",
		"i_iumc",
		"i_iump_mph",
		"i_iunw",
		"i_iunw1",
		"i_iuolc",
		"i_iuph",
		"i_iuph1",
		"i_iuport",
		"i_iuport1",
		"i_iuse",
		"i_iusell",
		"i_iusnet",
		"i_iuupl",
		"i_iuvod",
		"i_iuvote",
		"i_iux",
		"i_piacadv",
		"i_sbgood",
		"i_secfl",
		"i_secpif1",
		"i_secvir1",
		"i_skedu",
		"e_ade",
		"e_ads",
		"e_ads_loc",
		"e_ads_trk",
		"e_aeseu",
		"e_aws",
		"e_aws_cmp",
		"e_aws_cown",
		"e_aws_gt1_b2c_gt10ws",
		"e_awsval_cmp",
		"e_awsval_cown",
		"e_bd",
		"e_broad",
		"e_cc",
		"e_cc_ge_me",
		"e_crman",
		"e_ebuy",
		"e_ebuy2",
		"e_empmd1_gt0",
		"e_empmd1_gt20",
		"e_empmd_gt20",
		"e_envra",
		"e_erp",
		"e_erp1",
		"e_esell",
		"e_eturn",
		"e_fixbb",
		"e_iacc3g",
		"e_iacc3g_20",
		"e_igov",
		"e_igov2",
		"e_igov2pr",
		"e_igov2rt",
		"e_igov3",
		"e_igovrt",
		"e_inv",
		"e_inv2",
		"e_inv3sbg_ap_gt0",
		"e_invsnd",
		"e_invsndap",
		"e_ispdf_ge30",
		"e_ispdfokx",
		"e_ispdfokx_ge100",
		"e_it_mext",
		"e_itsp2",
		"e_itspvac2",
		"e_itt2",
		"e_pmd",
		"e_pmd_app",
		"e_ra",
		"e_rfac",
		"e_rfac1",
		"e_rfid",
		"e_rfid1",
		"e_rfpsas",
		"e_rfpsas1",
		"e_secpol",
		"e_secpol1",
		"e_sisc",
		"e_sisorp",
		"e_sm1_any",
		"e_sm1_ge2",
		"e_sm_any",
		"e_sm_ge2",
		"e_web",
		"e_webf2",
		"e_wsel25",
		"e_wsel50 ",
		"p_empmd",
		"p_empmd1",
		"p_iacc3g",
		"p_iuse",
		"p_mpmd"
	))

}