PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX dad: <http://semantic.digital-agenda-data.eu/def/property/>

select count(?obs) where {
 ?obs dad:indicator <http://semantic.digital-agenda-data.eu/codelist/indicator/${indicator}>;
 dad:breakdown <http://semantic.digital-agenda-data.eu/codelist/breakdown/${breakdown}>;
 dad:unit-measure <http://semantic.digital-agenda-data.eu/codelist/unit-measure/${unit}>
}
