PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX dad: <http://semantic.digital-agenda-data.eu/def/property/>

select ?groupnotation where {
 <http://semantic.digital-agenda-data.eu/codelist/indicator/${indicator}> 
    dad:membership [ dad:member-of [skos:notation ?groupnotation]]
}